#%RAML 1.0 NamedExample

value:
  
    price: 5500.0
    destination: Delhi
    departureDate: 2022-07-12T12:50:00Z
    source: Mumbai
    carPartner: REV
    seater: 5.0
    name: Baleno
    carNumber: MH032456
  
