#%RAML 1.0 NamedExample
Demoflightexample:

value:
  airline: Indigo
  flightCode: ER0945
  source: Bangalore
  destination: Delhi
  departureDate: Jan 1, 2022
  emptySeats: 14
  totalSeats: 150
  price: 350
  