#%RAML 1.0
title: FlightBookingAPI
mediaType: 
  - application/json
  - application/xml
protocols: [HTTP, HTTPS]
version: v1

securitySchemes:
  oauth_2_0: !include /securitySchemes/securityScheme.raml

traits:
  headerTrait: !include /traits/headerTrait.raml

types:
  Flight: !include DataTypes/flightdataType.raml
  FlightBooking: !include DataTypes/bookingdataType.raml
  Car: !include DataTypes/CarDataType.raml
  CarBooking: !include DataTypes/CarbookingdataType.raml
  Hotel: !include DataTypes/hoteldataType.raml
  HotelBooking: !include DataTypes/hotelBookingdataType.raml

securedBy:
      - oauth_2_0

/bookmyholiday:

  /cars:
    get:    
      queryParameters:
        source?: string
        destination?: string
        bookingDate?: string
      
      responses:
        200:
          body:
            application/json:
              type: Car
              example: !include CarDummyData/CarExample.raml
              

    /{carPartner}:

      get:
        queryParameters:
          source?: string
          destination?: string
  

        body:
          application/json:
            example: !include CarDummyData/CarDummyExample.raml
      
     

    

    /booking:
      description: To book a car
      post:
        body:
          application/json:
            type: CarBooking
            examples: !include CarBookingDummyData/DummyBookingExample.raml
        
        responses:
          201:
            body:
              application/json:
                example: 

                  message: Booking success
              

          
          
  
      /{bookingId}:
        description: To get booking details 
        get:
          responses:
            200:
              body:
                application/json:
                  type: CarBooking
                  examples: !include CarBookingDummyData/BookingeExample.raml

        
      
        delete:
          responses:
            202:
              body:
                application/json:
                  example:
                    message: Booking cancelled
        
        put:
          body:
            application/json:
              type: CarBooking
              example: !include CarBookingDummyData/updateBookingeExample.raml


          responses:
            204:
              body:
                application/json:
                  example: 
                    message: Booking updated successfully  
  
  /flights:
   
    get:

      queryParameters:
        source?: string
        destination?: string
        


      responses:
        200:
          body:
            application/json:
              type: Flight
              example: !include FlightDummyData/flightexample.raml

    
    post:
      body:
        application/json:
          type: Flight
          examples: !include FlightDummyData/Demoflightexample.raml

      responses: 
        201:
          body: 
            application/json:
              example:
                message: Flight added (but not really)          
    
    /{airline}:

      get:
        queryParameters:
          source?: string
          destination?: string
        body:
          application/json:
            example: !include FlightDummyData/flightexample.raml
      
      post:
      put:
      delete:

    /booking:
      description: To book flight
      post:
        body:
          application/json:
            type: FlightBooking
            examples: !include BookingDummyData/DummyBookingExample.raml
        
        responses:
          201:
            body:
              application/json:
                example: 

                  message: Flight Booking success
                  

            
            
    
      /{bookingId}:
        description: To get booking details 
        get:
          responses:
            200:
              body:
                application/json:
                  type: FlightBooking
                  examples: !include BookingDummyData/BookingeExample.raml

        
      
        delete:
          responses:
            202:
              body:
                application/json:
                  example:
                    message: Booking cancelled
        
        put:
          body:
            application/json:
              type: FlightBooking
              example: !include BookingDummyData/updateBookingeExample.raml


          responses:
            204:
              body:
                application/json:
                  example: 
                    message: Departure Date is updated !!
  
  /hotels:

      /{city}:
        get:
          responses:
            200:
              body:
                application/xml:
                  type: Hotel
                  example: !include HotelDummyData/hotelExample.raml

      /rating/{rating}:
        get:
          responses:
            200:
              body:
                application/xml:
                  type: Hotel
                  example: !include HotelDummyData/hotelByRatingExample.raml
      
      /booking:

        post:
          body:
            application/json:
              type: HotelBooking
              example: !include HotelBookingDummyData/hotelBookingexample.raml

          responses:
                201:
                  body:
                    application/json:
                      
                      example: 
                        message: Hotel booked successfully!!
              
        delete:
          responses:
            204:
              body:
                application/json:
                  example:
                    message: Booking cancelled!!
                                           
                
                    
                    

