#%RAML 1.0 NamedExample
value:
  
  bookingId: IND01501
  airline: Indigo
  travellerName: Rajat
  booking_mail: rajat@gmail.com
  departureDate: Jan 1,2022
  flightCode: ER0945
  source: Delhi
  destination: Bangalore